repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort

# Temporarily comment out Flake8 until ready to tackle it
# -   repo: https://github.com/pycqa/flake8
#     rev: 7.0.0
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-docstrings]
